### ISSUE TITLE
[pyclustering.cluster.birch] One dimention cluster allocation

### ISSUE THREAD

**Issue by annoviko** [annoviko/pyclustering#265]
Cluster are allocated in wrong way in case of one dimension data with measurement types:
- inter cluster distance;
- intra cluster distance;

Test are committed here: https://github.com/annoviko/pyclustering/commit/7af751f770327e6e5e3e3b1abf615b0634dffc60

Following tests shows the problem:
FAIL: testClusterAllocationOneAverageInterClusterDistance (__main__.Test)
FAIL: testClusterAllocationOneAverageIntraClusterDistance (__main__.Test)

Details:
FAIL: testClusterAllocationOneAverageInterClusterDistance (__main__.Test)
Traceback (most recent call last):
  File "/home/andrei/workspace/pyclustering/pyclustering/cluster/tests/birch_tests.py", line 101, in testClusterAllocationOneAverageInterClusterDistance
    self.templateClusterAllocationOneDimensionData(type_measurement = measurement_type.AVERAGE_INTER_CLUSTER_DISTANCE);
  File "/home/andrei/workspace/pyclustering/pyclustering/cluster/tests/birch_tests.py", line 92, in templateClusterAllocationOneDimensionData
    assert len(cluster) == 10;
AssertionError

FAIL: testClusterAllocationOneAverageIntraClusterDistance (__main__.Test)
Traceback (most recent call last):
  File "/home/andrei/workspace/pyclustering/pyclustering/cluster/tests/birch_tests.py", line 104, in testClusterAllocationOneAverageIntraClusterDistance
    self.templateClusterAllocationOneDimensionData(type_measurement = measurement_type.AVERAGE_INTRA_CLUSTER_DISTANCE);
  File "/home/andrei/workspace/pyclustering/pyclustering/cluster/tests/birch_tests.py", line 92, in templateClusterAllocationOneDimensionData
    assert len(cluster) == 10;
AssertionError

**Comment by annoviko** [comment]
Not a bug: https://github.com/annoviko/pyclustering/commit/e3c36d2269836ba0cf503c29a2b7e51e5afc4748

Incorrect parameters for inter- intra- distances.
