### ISSUE TITLE
[pyclustering.cluster.hsyncnet] Bug with cluster allocation without collecting dynamic

### ISSUE THREAD

**Issue by annoviko** [annoviko/pyclustering#285]
Bug with cluster allocation when dynamic is not collected. Applicable for python code only. Test scenario:

```
def templateClustering(self, path, number_clusters, expected_length_clusters, solver, initial_neighbors, increase_persent, collect_dynamic_flag, ccore_flag):
	result_testing = False;
	
	# If phases crosses each other because of random part of the network then we should try again.
	for _ in range(0, 3, 1):
		sample = read_sample(path);
		network = hsyncnet(sample, number_clusters, initial_type.EQUIPARTITION, initial_neighbors, increase_persent, ccore = ccore_flag);
		
		analyser = network.process(order = 0.997, solution = solver, collect_dynamic = collect_dynamic_flag);
		clusters = analyser.allocate_clusters(0.1);
		
		if (sum([len(cluster) for cluster in clusters]) != sum(expected_length_clusters)):
			continue;
		
		if (sorted([len(cluster) for cluster in clusters]) != expected_length_clusters):
			if (sorted([len(cluster) for cluster in clusters]) != sorted(expected_length_clusters)):
				continue;
		
		# Unit-test is passed
		result_testing = True;
		break;
	
	assert result_testing;

def testClusteringSampleSimple1WithoutCollecting(self):
        self.templateClustering(SIMPLE_SAMPLES.SAMPLE_SIMPLE1, 2, [5, 5], solve_type.FAST, 5, 0.3, False, False);
```

Output:

> ======================================================================
> ERROR: testClusteringSampleSimple1WithoutCollecting (__main__.Test)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "D:\userdata\annoviko\workspace\pyclustering\pyclustering\cluster\tests\hsyncnet_tests.py", line 69, in testClusteringSampleSimple1WithoutCollecting
>     self.templateClustering(SIMPLE_SAMPLES.SAMPLE_SIMPLE1, 2, [5, 5], solve_type.FAST, 5, 0.3, False, False);
>   File "D:\userdata\annoviko\workspace\pyclustering\pyclustering\cluster\tests\hsyncnet_tests.py", line 46, in templateClustering
>     clusters = analyser.allocate_clusters(0.1);
>   File "D:\userdata\annoviko\workspace\pyclustering\pyclustering\cluster\syncnet.py", line 78, in allocate_clusters
>     return self.allocate_sync_ensembles(eps);
>   File "D:\userdata\annoviko\workspace\pyclustering\pyclustering\nnet\sync.py", line 127, in allocate_sync_ensembles
>     number_oscillators = len(self._dynamic[0]);
> IndexError: list index out of range

**Comment by annoviko** [comment]
Have done at the revision https://github.com/annoviko/pyclustering/commit/6e24bee06050a13a5717c8d78c753814c76595c9 ,
