### ISSUE TITLE
[pyclustering.cluster.kmedians] Failure during processing data with rough initial medians

### ISSUE THREAD

**Issue by annoviko** [annoviko/pyclustering#286]
During testing with random data - bug has been detected. Failure occurs during processing SIMPLE_SAMPLE10 in case of rough initial medians. Test scenario:
```
    def testClusterAllocationSampleRoughMediansSimple10(self):
        initial_medians = [[0.0772944481804071, 0.05224990900863469], [1.6021689021213712, 1.0347579135245601], [2.3341008076636096, 1.280022869739064]];
        self.templateLengthProcessData(SIMPLE_SAMPLES.SAMPLE_SIMPLE10, initial_medians, None);
```

Stack output:
```
======================================================================
ERROR: testClusterAllocationSampleRoughMediansSimple10 (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrei/workspace/pyclustering/pyclustering/cluster/tests/kmedians_tests.py", line 182, in testClusterAllocationSampleRoughMediansSimple10
    self.templateLengthProcessData(SIMPLE_SAMPLES.SAMPLE_SIMPLE10, initial_medians, None);
  File "/home/andrei/workspace/pyclustering/pyclustering/cluster/tests/kmedians_tests.py", line 41, in templateLengthProcessData
    kmedians_instance.process();
  File "/home/andrei/workspace/pyclustering/pyclustering/cluster/kmedians.py", line 99, in process
    updated_centers = self.__update_medians();  # changes should be calculated before asignment
  File "/home/andrei/workspace/pyclustering/pyclustering/cluster/kmedians.py", line 182, in __update_medians
    index_median_second = sorted_cluster[relative_index_median + 1];
IndexError: list index out of range
```

This test is green for CCORE. Only pyclustering implementation has this bug.

**Comment by annoviko** [comment]
Have done at the revision https://github.com/annoviko/pyclustering/commit/8edca882acd8af5b679da45f61b55375860e51ba .
