### ISSUE TITLE
dbscan_examples.py crash python 2 & 3

### ISSUE THREAD

**Issue by oxbits** [annoviko/pyclustering#339]
dbscan_examples.py crash python 2 & 3

macos 10.12.4 (16E195)

$ python /Users/ox/_ws/ten_lines_spacy/p3_6e/lib/python3.6/site-packages/pyclustering/cluster/examples/dbscan_examples.py 

Traceback (most recent call last):
  File "/Users/ox/_ws/ten_lines_spacy/p3_6e/lib/python3.6/site-packages/pyclustering/cluster/examples/dbscan_examples.py", line 150, in <module>
    cluster_sample1();
  File "/Users/ox/_ws/ten_lines_spacy/p3_6e/lib/python3.6/site-packages/pyclustering/cluster/examples/dbscan_examples.py", line 55, in cluster_sample1
    template_clustering(0.4, 2, SIMPLE_SAMPLES.SAMPLE_SIMPLE1);
  File "/Users/ox/_ws/ten_lines_spacy/p3_6e/lib/python3.6/site-packages/pyclustering/cluster/examples/dbscan_examples.py", line 38, in template_clustering
    (ticks, _) = timedcall(dbscan_instance.process);
  File "/Users/ox/_ws/ten_lines_spacy/p3_6e/lib/python3.6/site-packages/pyclustering/utils/__init__.py", line 432, in timedcall
    result = executable_function(*args);
  File "/Users/ox/_ws/ten_lines_spacy/p3_6e/lib/python3.6/site-packages/pyclustering/cluster/dbscan.py", line 88, in process
    (self.__clusters, self.__noise) = wrapper.dbscan(self.__pointer_data, self.__eps, self.__neighbors, True);
  File "/Users/ox/_ws/ten_lines_spacy/p3_6e/lib/python3.6/site-packages/pyclustering/core/dbscan_wrapper.py", line 34, in dbscan
    package = ccore.dbscan_algorithm(pointer_data, c_double(eps), c_size_t(min_neighbors));
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, dbscan_algorithm): symbol not found

####

$ python2 /Users/ox/_ws/ten_lines_spacy/p3_6e/lib/python3.6/site-packages/pyclustering/cluster/examples/dbscan_examples.py 

Traceback (most recent call last):
  File "/Users/ox/_ws/ten_lines_spacy/p3_6e/lib/python3.6/site-packages/pyclustering/cluster/examples/dbscan_examples.py", line 150, in <module>
    cluster_sample1();
  File "/Users/ox/_ws/ten_lines_spacy/p3_6e/lib/python3.6/site-packages/pyclustering/cluster/examples/dbscan_examples.py", line 55, in cluster_sample1
    template_clustering(0.4, 2, SIMPLE_SAMPLES.SAMPLE_SIMPLE1);
  File "/Users/ox/_ws/ten_lines_spacy/p3_6e/lib/python3.6/site-packages/pyclustering/cluster/examples/dbscan_examples.py", line 38, in template_clustering
    (ticks, _) = timedcall(dbscan_instance.process);
  File "/usr/local/lib/python2.7/site-packages/pyclustering/utils/__init__.py", line 432, in timedcall
    result = executable_function(*args);
  File "/usr/local/lib/python2.7/site-packages/pyclustering/cluster/dbscan.py", line 88, in process
    (self.__clusters, self.__noise) = wrapper.dbscan(self.__pointer_data, self.__eps, self.__neighbors, True);
  File "/usr/local/lib/python2.7/site-packages/pyclustering/core/dbscan_wrapper.py", line 34, in dbscan
    package = ccore.dbscan_algorithm(pointer_data, c_double(eps), c_size_t(min_neighbors));
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, dbscan_algorithm): symbol not found

**Comment by annoviko** [comment]
Hello, @oxbits ,
MAC OS is not supported by the library. You can't use core of the library to have maximum performance, therefore you should switch off core usage (in this case python implementation of the algorithm will be used):
```python
dbscan_instance = dbscan(sample, radius, neighb, False);   # Last parameter should False
```

If you want to see example of DBSCAN, you need to change line 34: def template_clustering(radius, neighb, path, invisible_axes = False, ccore = **False**, show = True):
```python
def template_clustering(radius, neighb, path, invisible_axes = False, ccore = False, show = True):
```

**Comment by oxbits** [comment]
Hello @annoviko,

Totally worked for me, thank you for your response!

If one wanted to make it work on MacOS, one would need to work on the C++ code to get it to run on MacOS, is that true?

What IDE are you using to develop that part of the code?  Visual Studio?

**Comment by annoviko** [comment]
@oxbits ,
That's right, you can try to build the core of the library by yourself. You need to compile sources of the core that are located: **pyclustering/ccore** where you can find **makefile** for Linix 'makefile', and **Microsoft Visual Studio 2015** project 'ccore.sln' for Windows.

There is wiki page related to development, I hope you will find it useful: https://github.com/annoviko/pyclustering/wiki/Development

Most probably you will need to introduce changes in pyclustering/core/definitions (lines 35-38):
```python
# Path to DLL.
PATH_DLL_CCORE_64 = None;

if (_platform == "linux") or (_platform == "linux2"):
    PATH_DLL_CCORE_64 = core.__path__[0] + os.sep + "x64" + os.sep + "linux" + os.sep + "ccore.so";
elif (_platform == "win32"):
    PATH_DLL_CCORE_64 = core.__path__[0] + os.sep + "x64" + os.sep + "win" + os.sep + "ccore.dll";
```
Here library path is defined for each supported system (linux and windows). So, as I wrote before, you will need to add the same elif block for MAC OS.

**Comment by oxbits** [comment]
Awesome, I have not seen OPTICS for python elsewhere, so this is of keen interest.  

Is it true that the difference between DBSCAN and OPTICS is that the radius that determines reachability is fixed in DBSCAN but not fixed in OPTICS?  Are there other differences?

Do you prefer one over the other?

**Comment by annoviko** [comment]
@oxbits 
DBSCAN and OPTICS performs the same actions, BUT during clustering OPTICS build ordering diagram (reachability diagram) and IF you specified for OPTICS how many clusters should be allocated then OPTICS will calculate radius automatically to allocated specified amount of clusters. But it works only if radius was bigger than real.

You can found example (illustration) of that process in pyclustering documentation:
https://codedocs.xyz/annoviko/pyclustering/classpyclustering_1_1cluster_1_1optics_1_1optics.html

There is example of ordering diagram (also it is called as a reachability diagram):
![ordering-diagram](https://cloud.githubusercontent.com/assets/6785869/25485205/bac13462-2b65-11e7-9bee-b339a5c3142a.png)

As you can see if radius is bigger then we have "a full picture about clusters" and it is easier to extract required amount of clusters. From my point of view it is not easy to chose correct radius and amount of neighbors for DBSCAN, but in case of OPTICS, thus, if we know how many clusters should be extracted - then OPTICS is preferable and no need to think a lot about radius - just make it bigger - you have a right for mistake.
