### ISSUE TITLE
[xmeans_examples.py] Can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by ihavenoidea042** [annoviko/pyclustering#340]
I have a problem when I run the file xmeans_examples.py. I am using python 2.7. 

('Sample: ', '/usr/local/lib/python2.7/site-packages/pyclustering/samples/samples/SampleSimple01.txt', "\nInitial centers: '", True, "', Execution time: '", 0.0010860000000000314, "', Number of clusters:", 2, ',', 'BAYESIAN INFORMATION CRITERION', '\n')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pyclustering/cluster/examples/xmeans_examples.py", line 171, in <module>
    cluster_sample1();
  File "/usr/local/lib/python2.7/site-packages/pyclustering/cluster/examples/xmeans_examples.py", line 59, in cluster_sample1
    template_clustering(start_centers, SIMPLE_SAMPLES.SAMPLE_SIMPLE1, criterion = splitting_type.BAYESIAN_INFORMATION_CRITERION);
  File "/usr/local/lib/python2.7/site-packages/pyclustering/cluster/examples/xmeans_examples.py", line 53, in template_clustering
    visualizer.show();
  File "/usr/local/lib/python2.7/site-packages/pyclustering/cluster/__init__.py", line 262, in show
    ax = cluster_figure.add_subplot(grid_spec[index_canvas + canvas_shift]);
  File "/usr/local/lib/python2.7/site-packages/matplotlib/figure.py", line 1005, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/axes/_subplots.py", line 70, in __init__
    self.update_params()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/axes/_subplots.py", line 114, in update_params
    return_all=True)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/gridspec.py", line 425, in get_position
    gridspec.get_grid_positions(fig)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/gridspec.py", line 105, in get_grid_positions
    cellHeights = [cellH] * nrows
TypeError: can't multiply sequence by non-int of type 'float'

**Comment by ihavenoidea042** [comment]
The error has been fixed by reinstalling the package.

**Comment by annoviko** [comment]
Hello, @ihavenoidea042 , despite the issue is resolved, I would like to add that **pyclustering** library is not supported for python 2.7, only for python >= 3.4.
