### ISSUE TITLE
[pyclustering.cluster.kmeans] Impossible to visualize clusters

### ISSUE THREAD

**Issue by annoviko** [annoviko/pyclustering#465]
**Description**
Code:
```python
sample = read_sample(sample_file_path)

elbow_instance = elbow(sample, kmin, kmax)
elbow_instance.process()

amount_clusters = elbow_instance.get_amount()

centers = kmeans_plusplus_initializer(sample, amount_clusters).initialize()
kmeans_instance = kmeans(sample, centers)
clusters = kmeans_instance.get_clusters()
centers = kmeans_instance.get_centers()
kmeans_visualizer.show_clusters(sample, clusters, centers)
```

Output result of this code:
```
Traceback (most recent call last):
  File "D:/workspace/pyclustering/pyclustering/cluster/examples/elbow_examples.py", line 77, in <module>
    sample_simple_01()
  File "D:/workspace/pyclustering/pyclustering/cluster/examples/elbow_examples.py", line 65, in sample_simple_01
    elbow_analysis(SIMPLE_SAMPLES.SAMPLE_SIMPLE1, 1, 10)
  File "D:/workspace/pyclustering/pyclustering/cluster/examples/elbow_examples.py", line 61, in elbow_analysis
    kmeans_visualizer.show_clusters(sample, clusters, centers)
  File "D:\workspace\pyclustering\pyclustering\cluster\kmeans.py", line 170, in show_clusters
    kmeans_visualizer.__draw_centers(figure, offset, visualizer, centers, initial_centers)
  File "D:\workspace\pyclustering\pyclustering\cluster\kmeans.py", line 216, in __draw_centers
    ax = figure.get_axes()[offset]
IndexError: list index out of range

```

**Comment by annoviko** [comment]
Not a bug. K-Means wasn't started in the code example.
